import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    overlay: { flex: 1, justifyContent: "center", alignItems: "center" },
    backdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(0,0,0,0.4)" },
    card: { width: "92%", borderRadius: 16, backgroundColor: "#fff", padding: 16 },
    cardHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 12 },
    cardTitle: { fontSize: 18, fontWeight: "600", color: "#111827" },
    label: { fontSize: 14, fontWeight: "600", color: "#111827", marginBottom: 6 },
    subtleText: { fontSize: 12, color: "#6B7280", marginBottom: 8 },
    input: {
        borderWidth: 1,
        borderColor: "#E5E7EB",
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 10,
        fontSize: 14,
        color: "#111827",
    },
    tabsWrap: { flexDirection: "row", gap: 8, marginBottom: 4 },
    tab: {
        borderWidth: 1,
        borderColor: "#E5E7EB",
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 999,
        backgroundColor: "#fff",
    },
    tabActive: { backgroundColor: "#111827" },
    tabText: { fontSize: 13, color: "#111827" },
    tabTextActive: { color: "#fff" },
    primaryBtn: {
        marginTop: 14,
        backgroundColor: "#111827",
        paddingVertical: 12,
        borderRadius: 10,
        alignItems: "center",
    },
    primaryBtnText: { color: "#fff", fontWeight: "600" },
    secondaryBtn: {
        alignSelf: "flex-start",
        borderWidth: 1,
        borderColor: "#E5E7EB",
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 8,
    },
    secondaryBtnText: { color: "#111827", fontWeight: "600", fontSize: 12 },
    imageRow: { flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 8 },
    avatarWrapper: { width: 64, height: 64, borderRadius: 999, overflow: "hidden" },
    avatar: { width: "100%", height: "100%", borderRadius: 999 },
    avatarPlaceholder: { backgroundColor: "#F3F4F6", alignItems: "center", justifyContent: "center" },
});
