import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
    sheetContent: { padding: 16, gap: 12 },
    sheetTitle: { fontSize: 16, fontWeight: "700" },
    searchRow: { flexDirection: "row", gap: 8, alignItems: "center" },
    searchInput: {
        flex: 1,
        backgroundColor: "#F3F4F6",
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 12,
    },
    btn: {
        paddingHorizontal: 14,
        paddingVertical: 10,
        backgroundColor: "#2FBF71",
        borderRadius: 12,
    },
    btnText: { color: "#fff", fontWeight: "700" },
    listTitle: { fontWeight: "700" },
    listSub: { color: "#6b7280", marginTop: 4 },
    selectBtn: {
        alignSelf: "flex-start",
        marginTop: 10,
        paddingHorizontal: 12,
        paddingVertical: 8,
        backgroundColor: "#0C0C0C",
        borderRadius: 10,
    },
    selectBtnText: { color: "#fff", fontWeight: "600" },
    contentContainer: {
        paddingHorizontal: 16,
        paddingTop: 10,
        flex: 1,
        backgroundColor: "white",
    },
    searchBox: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#F5F5F5",
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 10,
        marginBottom: 14,
    },
    input: {
        flex: 1,
        fontSize: 14,
        color: "#333",
        marginHorizontal: 6,
    },
    sectionTitle: {
        fontWeight: "600",
        fontSize: 14,
        color: "#000",
        marginBottom: 8,
    },
    listItem: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: "#F0F0F0",
    },
    locationInfo: {
        flexDirection: "row",
        alignItems: "center",
        flex: 1,
    },
    locationTitle: {
        fontWeight: "600",
        fontSize: 14,
        color: "#000",
    },
    locationSubtitle: {
        fontSize: 12,
        color: "#777",
    },
    distance: {
        fontWeight: "600",
        fontSize: 13,
        color: "#2FBF71",
    },
});