import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#F3F5F7" },
  header: {
    backgroundColor: "#FFFFFF",
    paddingTop: Platform.OS === "ios" ? 54 : 18,
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#E9EDF2",
  },
  headerTitle: { fontSize: 22, fontWeight: "700", color: "#111" },
  headerTabs: { marginTop: 12, flexDirection: "row" },
  topTab: { paddingVertical: 8, paddingHorizontal: 16, borderRadius: 999, backgroundColor: "#F2F4F7", marginRight: 8 },
  topTabActive: { backgroundColor: "#111" },
  topTabText: { color: "#111", fontWeight: "600", fontSize: 12 },
  topTabTextActive: { color: "#FFF" },
  content: { padding: 16 },
  card: { backgroundColor: "#FFFFFF", borderRadius: 16, padding: 16, marginBottom: 16, elevation: 2 },
  cardTitle: { fontSize: 14, fontWeight: "800", marginBottom: 12, color: "#111", textTransform: 'uppercase' },
  input: {
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    padding: 12,
    backgroundColor: '#F8FAFC',
    marginBottom: 15,
    fontSize: 14,
  },
  primaryBtn: { backgroundColor: "#4C8DFF", padding: 14, borderRadius: 12, alignItems: 'center' },
  primaryBtnText: { color: "#FFF", fontWeight: "800" },
  requestRow: { flexDirection: "row", alignItems: "center", backgroundColor: "#FFF", padding: 12, borderRadius: 12, marginBottom: 10, borderWidth: 1, borderColor: "#F0F0F0" },
  requestMeta: { flex: 1 },
  requestChip: { paddingVertical: 4, paddingHorizontal: 10, borderRadius: 6 },
  progressTrack: { height: 8, backgroundColor: "#E5E7EB", borderRadius: 4, marginVertical: 10 },
  progressFill: { height: "100%", backgroundColor: "#4CAF50", borderRadius: 4 },
  grid: { flexDirection: "row", flexWrap: "wrap", justifyContent: 'space-between' },
  statCard: { width: '48%', backgroundColor: '#FFF', padding: 16, borderRadius: 16, marginBottom: 15, alignItems: 'center' },
  statNumber: { fontSize: 24, fontWeight: 'bold', color: '#111' },
  statLabel: { fontSize: 12, color: '#666', marginTop: 4 },
});