import { Platform, StyleSheet } from "react-native";

const NAVY = "#0f172a";
const CYAN = "#06b6d4";
const SOFT = "#ecfeff";

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#f1f5f9" },
  header: {
    backgroundColor: NAVY,
    paddingTop: Platform.OS === "ios" ? 50 : 30,
    paddingBottom: 22,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    overflow: "hidden",
  },
  headerGlow: {
    position: "absolute",
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: "rgba(6,182,212,0.15)",
    top: -30,
    right: -20,
  },
  headerTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.1)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  headerTitle: { color: "#FFF", fontWeight: "900", fontSize: 19, letterSpacing: 0.3 },
  headerSub: { color: "rgba(255,255,255,0.72)", fontSize: 12, marginTop: 6, fontWeight: "600" },
  secureBadge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "rgba(6,182,212,0.2)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    marginTop: 10,
    borderWidth: 1,
    borderColor: "rgba(6,182,212,0.3)",
  },
  secureBadgeText: { color: "#cffafe", fontSize: 10, fontWeight: "800", marginLeft: 5 },
  tabsRow: { marginTop: 14 },
  tabBtn: {
    paddingVertical: 9,
    paddingHorizontal: 14,
    borderRadius: 12,
    marginRight: 8,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  tabBtnActive: { backgroundColor: "#FFF" },
  tabText: { color: "rgba(255,255,255,0.65)", fontSize: 10, fontWeight: "800", letterSpacing: 0.3 },
  tabTextActive: { color: NAVY },
  body: { padding: 16, paddingBottom: 40 },
  card: {
    backgroundColor: "#FFF",
    borderRadius: 20,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    ...Platform.select({
      ios: { shadowColor: NAVY, shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.08, shadowRadius: 12 },
      android: { elevation: 4 },
    }),
  },
  sectionHeader: { flexDirection: "row", alignItems: "center", marginBottom: 14 },
  sectionIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: SOFT,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  sectionTitle: { fontSize: 13, fontWeight: "900", color: NAVY, letterSpacing: 0.5, flex: 1 },
  statusHero: {
    backgroundColor: NAVY,
    borderRadius: 18,
    padding: 16,
    marginBottom: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  statusHeroLabel: { color: "rgba(255,255,255,0.65)", fontSize: 11, fontWeight: "700" },
  statusHeroValue: { color: "#FFF", fontSize: 18, fontWeight: "900", marginTop: 4 },
  liveDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: "#22c55e" },
  featureRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f8fafc",
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  featureIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: SOFT,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
    borderWidth: 1,
    borderColor: "#a5f3fc",
  },
  itemTitle: { fontSize: 15, fontWeight: "800", color: "#0f172a" },
  itemMeta: { fontSize: 12, color: "#64748b", marginTop: 3, lineHeight: 18 },
  statRow: { flexDirection: "row", gap: 10, marginBottom: 14 },
  statBox: {
    flex: 1,
    backgroundColor: "#f8fafc",
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    alignItems: "center",
  },
  statValue: { fontSize: 18, fontWeight: "900", color: CYAN },
  statLabel: { fontSize: 10, fontWeight: "700", color: "#64748b", marginTop: 2, textAlign: "center" },
  roleCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: "#f8fafc",
    borderRadius: 14,
    padding: 12,
    marginBottom: 8,
    borderLeftWidth: 4,
    borderLeftColor: CYAN,
  },
  snapshotCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f8fafc",
    borderRadius: 14,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  snapshotCardSelected: {
    borderColor: CYAN,
    backgroundColor: SOFT,
  },
  snapshotType: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    backgroundColor: NAVY,
    marginRight: 10,
  },
  snapshotTypeText: { color: "#FFF", fontSize: 9, fontWeight: "900" },
  infoBanner: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: SOFT,
    borderRadius: 12,
    padding: 10,
    marginTop: 10,
    marginBottom: 4,
  },
  infoBannerText: { fontSize: 11, color: NAVY, fontWeight: "700", marginLeft: 8, flex: 1 },
  actionBtn: {
    backgroundColor: NAVY,
    borderRadius: 14,
    paddingVertical: 13,
    alignItems: "center",
    marginTop: 12,
    flexDirection: "row",
    justifyContent: "center",
    ...Platform.select({
      ios: { shadowColor: NAVY, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.25, shadowRadius: 8 },
      android: { elevation: 4 },
    }),
  },
  actionBtnText: { color: "#FFF", fontWeight: "900", fontSize: 12, letterSpacing: 0.6 },
  actionBtnOutline: {
    borderRadius: 14,
    paddingVertical: 13,
    alignItems: "center",
    marginTop: 8,
    borderWidth: 1.5,
    borderColor: CYAN,
    backgroundColor: "#FFF",
  },
  actionBtnOutlineText: { color: CYAN, fontWeight: "900", fontSize: 12, letterSpacing: 0.4 },
});
