import { Platform, StyleSheet } from "react-native";

const GREEN = "#0f4c3a";
const ACCENT = "#ec4899";
const SOFT = "#ecfdf5";

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#f0faf6" },
  header: {
    backgroundColor: GREEN,
    paddingTop: Platform.OS === "ios" ? 50 : 30,
    paddingBottom: 22,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    overflow: "hidden",
  },
  headerGlow: {
    position: "absolute",
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: "rgba(236,72,153,0.18)",
    top: -40,
    right: -30,
  },
  headerGlow2: {
    position: "absolute",
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "rgba(255,255,255,0.06)",
    bottom: 10,
    left: -20,
  },
  headerTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.14)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  headerTitle: { color: "#FFF", fontWeight: "900", fontSize: 20, letterSpacing: 0.3 },
  headerSub: { color: "rgba(255,255,255,0.78)", fontSize: 12, marginTop: 6, fontWeight: "600", lineHeight: 18 },
  careBadge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "rgba(236,72,153,0.25)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    marginTop: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
  },
  careBadgeText: { color: "#fce7f3", fontSize: 10, fontWeight: "800", marginLeft: 5 },
  tabsRow: { marginTop: 14 },
  tabBtn: {
    paddingVertical: 9,
    paddingHorizontal: 14,
    borderRadius: 12,
    marginRight: 8,
    backgroundColor: "rgba(255,255,255,0.1)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  tabBtnActive: { backgroundColor: "#FFF", borderColor: "#FFF" },
  tabText: { color: "rgba(255,255,255,0.72)", fontSize: 10, fontWeight: "800", letterSpacing: 0.4 },
  tabTextActive: { color: GREEN },
  body: { padding: 16, paddingBottom: 40 },
  heroRow: { flexDirection: "row", gap: 10, marginBottom: 14 },
  heroStat: {
    flex: 1,
    backgroundColor: "#FFF",
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: "#d1fae5",
    ...Platform.select({
      ios: { shadowColor: GREEN, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.08, shadowRadius: 8 },
      android: { elevation: 3 },
    }),
  },
  heroStatValue: { fontSize: 20, fontWeight: "900", color: GREEN },
  heroStatLabel: { fontSize: 10, fontWeight: "700", color: "#6b7280", marginTop: 2 },
  card: {
    backgroundColor: "#FFF",
    borderRadius: 20,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "#e5f5ef",
    ...Platform.select({
      ios: { shadowColor: "#000", shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.06, shadowRadius: 12 },
      android: { elevation: 4 },
    }),
  },
  sectionHeader: { flexDirection: "row", alignItems: "center", marginBottom: 14 },
  sectionIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: SOFT,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  sectionTitle: { fontSize: 13, fontWeight: "900", color: GREEN, letterSpacing: 0.6, flex: 1 },
  itemTitle: { fontSize: 15, fontWeight: "800", color: "#111827" },
  itemMeta: { fontSize: 12, color: "#6B7280", marginTop: 3, lineHeight: 18 },
  listCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fafffe",
    borderRadius: 16,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#e8f5ef",
  },
  listCardSelected: {
    borderColor: ACCENT,
    backgroundColor: "#fff5f9",
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: SOFT,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
    borderWidth: 1,
    borderColor: "#bbf7d0",
  },
  avatarText: { fontSize: 14, fontWeight: "900", color: GREEN },
  chip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    backgroundColor: SOFT,
    borderWidth: 1,
    borderColor: "#bbf7d0",
  },
  chipText: { fontSize: 10, fontWeight: "800", color: GREEN },
  resourceRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#f0fdf4",
  },
  resourceIcon: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: "#fdf2f8",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
    marginTop: 2,
  },
  tipCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: "#fafffe",
    borderRadius: 14,
    padding: 12,
    marginBottom: 8,
    borderLeftWidth: 4,
    borderLeftColor: ACCENT,
  },
  tipNumber: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: GREEN,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  tipNumberText: { color: "#FFF", fontSize: 11, fontWeight: "900" },
  ngoCard: {
    backgroundColor: "#fafffe",
    borderRadius: 16,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#e8f5ef",
  },
  helplineRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 8,
    backgroundColor: SOFT,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    alignSelf: "flex-start",
  },
  helplineText: { fontSize: 12, fontWeight: "800", color: GREEN, marginLeft: 6 },
  actionBtn: {
    backgroundColor: GREEN,
    borderRadius: 14,
    paddingVertical: 13,
    paddingHorizontal: 16,
    alignItems: "center",
    marginTop: 12,
    flexDirection: "row",
    justifyContent: "center",
    ...Platform.select({
      ios: { shadowColor: GREEN, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8 },
      android: { elevation: 4 },
    }),
  },
  actionBtnText: { color: "#FFF", fontWeight: "900", fontSize: 12, letterSpacing: 0.8 },
  input: {
    borderWidth: 1,
    borderColor: "#d1fae5",
    backgroundColor: "#fafffe",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: "#111827",
    minHeight: 100,
    textAlignVertical: "top",
    fontSize: 14,
    lineHeight: 20,
  },
  emptyWrap: { alignItems: "center", paddingVertical: 24 },
  emptyText: { fontSize: 13, color: "#9ca3af", marginTop: 8, fontWeight: "600" },
});
