import { Platform, StyleSheet } from "react-native";

const GREEN = "#0f4c3a";
const GOLD = "#f59e0b";
const CREAM = "#fffbeb";

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#fafaf8" },
  header: {
    backgroundColor: GREEN,
    paddingTop: Platform.OS === "ios" ? 50 : 30,
    paddingBottom: 22,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    overflow: "hidden",
  },
  headerGlow: {
    position: "absolute",
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: "rgba(245,158,11,0.15)",
    top: -35,
    right: -25,
  },
  headerTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.14)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  headerTitle: { color: "#FFF", fontWeight: "900", fontSize: 20, letterSpacing: 0.3 },
  headerSub: { color: "rgba(255,255,255,0.75)", fontSize: 12, marginTop: 6, fontWeight: "600" },
  voiceBadge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "rgba(245,158,11,0.22)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    marginTop: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  voiceBadgeText: { color: "#fef3c7", fontSize: 10, fontWeight: "800", marginLeft: 5 },
  tabsRow: { marginTop: 14 },
  tabBtn: {
    paddingVertical: 9,
    paddingHorizontal: 14,
    borderRadius: 12,
    marginRight: 8,
    backgroundColor: "rgba(255,255,255,0.1)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  tabBtnActive: { backgroundColor: "#FFF" },
  tabText: { color: "rgba(255,255,255,0.72)", fontSize: 10, fontWeight: "800", letterSpacing: 0.3 },
  tabTextActive: { color: GREEN },
  body: { padding: 16, paddingBottom: 40 },
  card: {
    backgroundColor: "#FFF",
    borderRadius: 20,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "#f0f0eb",
    ...Platform.select({
      ios: { shadowColor: "#000", shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.06, shadowRadius: 12 },
      android: { elevation: 4 },
    }),
  },
  sectionHeader: { flexDirection: "row", alignItems: "center", marginBottom: 14 },
  sectionIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: CREAM,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  sectionTitle: { fontSize: 13, fontWeight: "900", color: GREEN, letterSpacing: 0.5, flex: 1 },
  ratingHero: {
    alignItems: "center",
    backgroundColor: CREAM,
    borderRadius: 20,
    paddingVertical: 20,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "#fde68a",
  },
  ratingCircle: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: "#FFF",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 3,
    borderColor: GOLD,
    marginBottom: 10,
    ...Platform.select({
      ios: { shadowColor: GOLD, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.2, shadowRadius: 8 },
      android: { elevation: 3 },
    }),
  },
  ratingBig: { fontSize: 32, fontWeight: "900", color: GOLD },
  starsRow: { flexDirection: "row", alignItems: "center", justifyContent: "center", marginBottom: 4 },
  starBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 4,
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderColor: "#fde68a",
  },
  starBtnActive: { backgroundColor: CREAM, borderColor: GOLD },
  reviewMeta: { fontSize: 12, color: "#6B7280", marginTop: 4, lineHeight: 18, textAlign: "center" },
  input: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    backgroundColor: "#fafaf8",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: "#111827",
    minHeight: 110,
    textAlignVertical: "top",
    fontSize: 14,
    lineHeight: 20,
  },
  anonCard: {
    backgroundColor: "#f0fdf4",
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: "#bbf7d0",
    marginTop: 10,
  },
  row: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  actionBtn: {
    backgroundColor: GREEN,
    borderRadius: 14,
    paddingVertical: 13,
    alignItems: "center",
    marginTop: 14,
    flexDirection: "row",
    justifyContent: "center",
    ...Platform.select({
      ios: { shadowColor: GREEN, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.25, shadowRadius: 8 },
      android: { elevation: 4 },
    }),
  },
  actionBtnText: { color: "#FFF", fontWeight: "900", fontSize: 12, letterSpacing: 0.6 },
  statGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginBottom: 4 },
  statCard: {
    width: "47%",
    backgroundColor: "#fafffe",
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: "#e8f5ef",
  },
  statCardWide: {
    width: "100%",
    backgroundColor: CREAM,
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: "#fde68a",
    marginBottom: 10,
  },
  statValue: { fontSize: 22, fontWeight: "900", color: GREEN },
  statValueGold: { fontSize: 28, fontWeight: "900", color: GOLD },
  statLabel: { fontSize: 10, fontWeight: "800", color: "#6b7280", marginTop: 4, letterSpacing: 0.3 },
  pipelineRow: { flexDirection: "row", alignItems: "center", marginTop: 10, marginBottom: 4 },
  pipelineStep: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 8,
    backgroundColor: "#f0fdf4",
    borderRadius: 10,
    marginHorizontal: 2,
  },
  pipelineText: { fontSize: 8, fontWeight: "900", color: GREEN, marginTop: 4 },
  reviewTitle: { fontSize: 14, fontWeight: "800", color: "#111827" },
  queueItem: {
    backgroundColor: "#fafaf8",
    borderRadius: 14,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#f0f0eb",
  },
  quoteBox: {
    backgroundColor: "#FFF",
    borderLeftWidth: 3,
    borderLeftColor: GOLD,
    paddingLeft: 10,
    paddingVertical: 6,
    marginTop: 6,
    borderRadius: 4,
  },
  quoteText: { fontSize: 12, color: "#4b5563", fontStyle: "italic", lineHeight: 18 },
  statusChip: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    alignSelf: "flex-start",
    marginTop: 8,
  },
  statusChipText: { fontSize: 10, fontWeight: "900" },
  adminActionsRow: { flexDirection: "row", flexWrap: "wrap", marginTop: 10, gap: 8 },
  adminActionBtn: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: "#eaf4ea",
    borderWidth: 1,
    borderColor: "#bbf7d0",
  },
  adminActionBtnText: { fontSize: 10, fontWeight: "900", color: GREEN },
  reviewCard: {
    backgroundColor: "#fafffe",
    borderRadius: 14,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#e8f5ef",
  },
  starsInline: { flexDirection: "row", marginTop: 4 },
});
