import { Platform, StyleSheet } from "react-native";

export const HEADER_GREEN = "#0f4c3a";
export const HEADER_ACCENT = "#ec4899";

export const fancyHeaderStyles = StyleSheet.create({
  header: {
    backgroundColor: HEADER_GREEN,
    paddingTop: Platform.OS === "ios" ? 50 : 30,
    paddingBottom: 22,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    overflow: "hidden",
  },
  headerGlow: {
    position: "absolute",
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: "rgba(236,72,153,0.18)",
    top: -40,
    right: -30,
  },
  headerGlow2: {
    position: "absolute",
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "rgba(255,255,255,0.06)",
    bottom: 10,
    left: -20,
  },
  headerTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.14)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  headerTitle: {
    color: "#FFF",
    fontWeight: "900",
    fontSize: 20,
    letterSpacing: 0.3,
    flex: 1,
    textAlign: "center",
  },
  headerSub: {
    color: "rgba(255,255,255,0.78)",
    fontSize: 12,
    marginTop: 6,
    fontWeight: "600",
    lineHeight: 18,
  },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "rgba(236,72,153,0.25)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    marginTop: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
  },
  badgeText: {
    color: "#fce7f3",
    fontSize: 10,
    fontWeight: "800",
    marginLeft: 5,
    letterSpacing: 0.5,
  },
  tabsRow: { marginTop: 14 },
  tabBtn: {
    paddingVertical: 9,
    paddingHorizontal: 14,
    borderRadius: 12,
    marginRight: 8,
    backgroundColor: "rgba(255,255,255,0.1)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  tabBtnActive: { backgroundColor: "#FFF", borderColor: "#FFF" },
  tabText: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.4,
  },
  tabTextActive: { color: HEADER_GREEN },
  footer: { marginTop: 14 },
  rightSlot: { width: 40, alignItems: "flex-end" },
  leftSlot: { width: 40 },
});
